#!/bin/bash
#-v

rm -rf armeabi
rm -rf armeabi-v7a
rm -rf mips
rm -rf x86

rm libARDataTransfer.jar
rm libARDiscovery.jar
rm libARUtils.jar
rm libARSAL.jar
rm libcurl.jar
rm libARMedia.jar
rm libARDataTransfer_dbg.jar
rm libARDiscovery_dbg.jar
rm libARUtils_dbg.jar
rm libARSAL_dbg.jar
rm libcurl_dbg.jar
rm libARMedia_dbg.jar

if [ -z "$1" ]
then
    cp -v ../../../../ARBuildUtils/Targets/Android/Install/jars/release/libARDataTransfer.jar .
    cp -v ../../../../ARBuildUtils/Targets/Android/Install/jars/release/libARDiscovery.jar .
    cp -v ../../../../ARBuildUtils/Targets/Android/Install/jars/release/libARUtils.jar .
    cp -v ../../../../ARBuildUtils/Targets/Android/Install/jars/release/libARSAL.jar .
    cp -v ../../../../ARBuildUtils/Targets/Android/Install/jars/release/libARMedia.jar .
    #cp -v ../../../../ARBuildUtils/Targets/Android/Install/jars/release/libcurl.jar .
else if [[ "$1" -eq "d" ]]
then
    cp -v ../../../../../ARBuildUtils/Targets/Android/Install/jars/debug/libARDataTransfer_dbg.jar .
    cp -v ../../../../../ARBuildUtils/Targets/Android/Install/jars/debug/libARDiscovery_dbg.jar .
    cp -v ../../../../../ARBuildUtils/Targets/Android/Install/jars/debug/libARUtils_dbg.jar .
    cp -v ../../../../../ARBuildUtils/Targets/Android/Install/jars/debug/libARSAL_dbg.jar .
    cp -v ../../../../ARBuildUtils/Targets/Android/Install/jars/release/libARMedia_dbg.jar .
    #cp -v ../../../../../ARBuildUtils/Targets/Android/Install/jars/debug/libcurl_dbg.jar .
else
echo "-d for debug jars"
fi
fi

#cp -v ../../../../ARBuildUtils/Targets/Android/Install/jars/release/libARDataTransfer.jar .
#cp -v ../../../../ARBuildUtils/Targets/Android/Install/jars/release/libARDiscovery.jar .
#cp -v ../../../../ARBuildUtils/Targets/Android/Install/jars/release/libARUtils.jar .
#cp -v ../../../../ARBuildUtils/Targets/Android/Install/jars/release/libARSAL.jar .
#cp -v ../../../../ARBuildUtils/Targets/Android/Install/jars/release/libARMedia.jar .
cp -v ../../../../ARBuildUtils/Targets/Android/Install/jars/release/libcurl.jar .

./extractJars.bash

